// ignore_for_file: file_names

class MyData {
  List<Map<String, String>> data = [
    {
      "nameEnglish": "revelation",
      "nameBengali": "১/ ওহীর সূচনা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "1",
      "chSerial": "1",
      "bookId": "1",
      "hadith_number": "6",
      "range_start": "1",
      "range_end": "6",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Belief ",
      "nameBengali": "২/ ঈমান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "4",
      "chSerial": "2",
      "bookId": "1",
      "hadith_number": "50",
      "range_start": "7",
      "range_end": "56",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Knowledge",
      "nameBengali": "৩/ ইলম বা জ্ঞান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "6",
      "chSerial": "3",
      "bookId": "1",
      "hadith_number": "80",
      "range_start": "57",
      "range_end": "136",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Ablutions (Wudu)",
      "nameBengali": "৪/ উযূ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "7",
      "chSerial": "4",
      "bookId": "1",
      "hadith_number": "109",
      "range_start": "137",
      "range_end": "245",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Bathing (Ghusl)",
      "nameBengali": "৫/ গোসল",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "8",
      "chSerial": "5",
      "bookId": "1",
      "hadith_number": "44",
      "range_start": "246",
      "range_end": "289",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Menstrual Periods",
      "nameBengali": "৬/ হায়য",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "9",
      "chSerial": "6",
      "bookId": "1",
      "hadith_number": "37",
      "range_start": "290",
      "range_end": "326",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Rubbing hands and feet with dust (Tayammum)",
      "nameBengali": "৭/ তায়াম্মুম",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "10",
      "chSerial": "7",
      "bookId": "1",
      "hadith_number": "15",
      "range_start": "327",
      "range_end": "341",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Prayers (Salat)",
      "nameBengali": "৮/ সালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "11",
      "chSerial": "8",
      "bookId": "1",
      "hadith_number": "155",
      "range_start": "342",
      "range_end": "496",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Time of Prayers ",
      "nameBengali": "৯/ সালাতের ওয়াক্তসমূহ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "12",
      "chSerial": "9",
      "bookId": "1",
      "hadith_number": "79",
      "range_start": "497",
      "range_end": "575",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Call of Prayers (Adhaan)",
      "nameBengali": "১০/ আযান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "13",
      "chSerial": "10",
      "bookId": "1",
      "hadith_number": "256",
      "range_start": "576",
      "range_end": "831",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Friday prayer (Jumu'a)",
      "nameBengali": "১১/ জুমু'আ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "14",
      "chSerial": "11",
      "bookId": "1",
      "hadith_number": "63",
      "range_start": "832",
      "range_end": "894",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Fear Prayer",
      "nameBengali": "১২/ শত্রুভীতি অবস্থায় সালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "15",
      "chSerial": "12",
      "bookId": "1",
      "hadith_number": "6",
      "range_start": "895",
      "range_end": "900",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "The Two Festivals (Eids)",
      "nameBengali": "১৩/ দুই ঈদ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "16",
      "chSerial": "13",
      "bookId": "1",
      "hadith_number": "36",
      "range_start": "901",
      "range_end": "936",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Witr Prayer",
      "nameBengali": "১৪/ বিতর সালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "17",
      "chSerial": "14",
      "bookId": "1",
      "hadith_number": "14",
      "range_start": "937",
      "range_end": "950",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Invoking Allah for Rain (Istisqaa)",
      "nameBengali": "১৫/ বৃষ্টির জন্য দু'আ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "18",
      "chSerial": "15",
      "bookId": "1",
      "hadith_number": "32",
      "range_start": "951",
      "range_end": "982",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Eclipses",
      "nameBengali": "১৬/ সূর্যগ্রহন",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "19",
      "chSerial": "16",
      "bookId": "1",
      "hadith_number": "23",
      "range_start": "983",
      "range_end": "1005",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Prostration During Recital of Qur'an",
      "nameBengali": "১৭/ কুরআন তিলওয়াতে সিজদা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "20",
      "chSerial": "17",
      "bookId": "1",
      "hadith_number": "13",
      "range_start": "1006",
      "range_end": "1018",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Shortening The Prayer (At-Taqseer)",
      "nameBengali": "১৮/ সালাতে কসর করা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "21",
      "chSerial": "18",
      "bookId": "1",
      "hadith_number": "35",
      "range_start": "1019",
      "range_end": "1053",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Prayer At Night (Tahajjud)",
      "nameBengali": "১৯/ তাহাজ্জুদ বা রাতের সালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "22",
      "chSerial": "19",
      "bookId": "1",
      "hadith_number": "111",
      "range_start": "1054",
      "range_end": "1164",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Funerals (Al-Janaa'Iz)",
      "nameBengali": "২০/ জানাযা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "23",
      "chSerial": "20",
      "bookId": "1",
      "hadith_number": "148",
      "range_start": "1165",
      "range_end": "1312",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Obligatory Charity Tax (Zakat)",
      "nameBengali": "২১/ যাকাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "24",
      "chSerial": "21",
      "bookId": "1",
      "hadith_number": "112",
      "range_start": "1313",
      "range_end": "1424",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Pilgrimmage",
      "nameBengali": "২২/ হজ্ব (হাজ্জ)",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "25",
      "chSerial": "22",
      "bookId": "1",
      "hadith_number": "345",
      "range_start": "1425",
      "range_end": "1769",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Fasting",
      "nameBengali": "২৩/ সাওম বা রোজা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "26",
      "chSerial": "23",
      "bookId": "1",
      "hadith_number": "112",
      "range_start": "1770",
      "range_end": "1881",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Praying at Night in Ramadaan (Taraweeh) ",
      "nameBengali": "২৪/ তারাবীহর সালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "27",
      "chSerial": "24",
      "bookId": "1",
      "hadith_number": "16",
      "range_start": "1882",
      "range_end": "1897",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Retiring to a Mosque for Remembrance of Allah (I'tikaf) ",
      "nameBengali": "২৫/ ই'তিকাফ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "28",
      "chSerial": "25",
      "bookId": "1",
      "hadith_number": "21",
      "range_start": "1898",
      "range_end": "1918",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Sales and Trade",
      "nameBengali": "২৬/ ক্রয় - বিক্রয়",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "29",
      "chSerial": "26",
      "bookId": "1",
      "hadith_number": "178",
      "range_start": "1919",
      "range_end": "2096",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish":
          "Sales In which A Price Is Paid For Goods To Be Delivered Later (As-Salam)",
      "nameBengali": "২৭/ সলম",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "30",
      "chSerial": "27",
      "bookId": "1",
      "hadith_number": "17",
      "range_start": "2097",
      "range_end": "2113",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Shufa",
      "nameBengali": "২৮/ শুফআ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "31",
      "chSerial": "28",
      "bookId": "1",
      "hadith_number": "3",
      "range_start": "2114",
      "range_end": "2116",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Hiring",
      "nameBengali": "২৯/ ইজারা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "32",
      "chSerial": "29",
      "bookId": "1",
      "hadith_number": "25",
      "range_start": "2117",
      "range_end": "2141",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish":
          "Transfer Of A Debt From One Person To Another (Al-Hawaala)",
      "nameBengali": "৩০/ হাওয়ালা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "33",
      "chSerial": "30",
      "bookId": "1",
      "hadith_number": "3",
      "range_start": "2142",
      "range_end": "2144",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Kafalah",
      "nameBengali": "৩১/ যামিন হওয়া",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "34",
      "chSerial": "31",
      "bookId": "1",
      "hadith_number": "7",
      "range_start": "2145",
      "range_end": "2151",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Representation, Authorization, Business By Proxy ",
      "nameBengali": "৩২/ ওয়াকালাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "35",
      "chSerial": "32",
      "bookId": "1",
      "hadith_number": "17",
      "range_start": "2152",
      "range_end": "2168",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Agriculture",
      "nameBengali": "৩৩/ বর্গাচাষ",
      "lastUpdate": "2015-06-02",
      "isActive": "1",
      "id": "36",
      "chSerial": "33",
      "bookId": "1",
      "hadith_number": "28",
      "range_start": "2169",
      "range_end": "2196",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Distribution Of Water",
      "nameBengali": "৩৪/ পানি সিঞ্চন ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "37",
      "chSerial": "34",
      "bookId": "1",
      "hadith_number": "30",
      "range_start": "2197",
      "range_end": "2226",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Loans",
      "nameBengali": "৩৫/ ঋন গ্রহন",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "38",
      "chSerial": "35",
      "bookId": "1",
      "hadith_number": "23",
      "range_start": "2227",
      "range_end": "2249",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Khusoomat",
      "nameBengali": "৩৬/ কলহ- বিবাদ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "39",
      "chSerial": "36",
      "bookId": "1",
      "hadith_number": "15",
      "range_start": "2250",
      "range_end": "2264",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Lost Things Picked Up By Someone (Luqaata)",
      "nameBengali": "৩৭/ পড়ে থাকা বস্তু উঠান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "40",
      "chSerial": "37",
      "bookId": "1",
      "hadith_number": "13",
      "range_start": "2265",
      "range_end": "2277",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Oppressions",
      "nameBengali": "৩৮/ যুলম ও কিসাস",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "41",
      "chSerial": "38",
      "bookId": "1",
      "hadith_number": "43",
      "range_start": "2278",
      "range_end": "2320",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Partnership",
      "nameBengali": "৩৯/ অংশীদারিত্ব",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "42",
      "chSerial": "39",
      "bookId": "1",
      "hadith_number": "22",
      "range_start": "2321",
      "range_end": "2342",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Mortgagging",
      "nameBengali": "৪০/ বন্ধক",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "43",
      "chSerial": "40",
      "bookId": "1",
      "hadith_number": "8",
      "range_start": "2343",
      "range_end": "2350",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Manumission Of Slaves",
      "nameBengali": "৪১/ গোলাম আযাদ করা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "44",
      "chSerial": "41",
      "bookId": "1",
      "hadith_number": "40",
      "range_start": "2351",
      "range_end": "2390",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Makttib",
      "nameBengali": "৪২/ মুকাতাব",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "45",
      "chSerial": "42",
      "bookId": "1",
      "hadith_number": "5",
      "range_start": "2391",
      "range_end": "2395",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Gifts",
      "nameBengali": "৪৩/ হিবা (উপহার) প্রদান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "46",
      "chSerial": "43",
      "bookId": "1",
      "hadith_number": "65",
      "range_start": "2396",
      "range_end": "2460",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Witnesses",
      "nameBengali": "৪৪/ শাহাদাত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "47",
      "chSerial": "44",
      "bookId": "1",
      "hadith_number": "50",
      "range_start": "2461",
      "range_end": "2510",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Peacemaking",
      "nameBengali": "৪৫/ সন্ধি",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "48",
      "chSerial": "45",
      "bookId": "1",
      "hadith_number": "19",
      "range_start": "2511",
      "range_end": "2529",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Conditions",
      "nameBengali": "৪৬/ শর্তাবলী",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "49",
      "chSerial": "46",
      "bookId": "1",
      "hadith_number": "21",
      "range_start": "2530",
      "range_end": "2550",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Wills And Testaments (Wasaayaa)",
      "nameBengali": "৪৭/ অসিয়াত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "50",
      "chSerial": "47",
      "bookId": "1",
      "hadith_number": "40",
      "range_start": "2551",
      "range_end": "2590",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Fighting For The Cause Of Allah (Jihaad)",
      "nameBengali": "৪৮/ জিহাদ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "51",
      "chSerial": "48",
      "bookId": "1",
      "hadith_number": "373",
      "range_start": "2591",
      "range_end": "2963",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Beginning Of Creation",
      "nameBengali": "৪৯/ সৃষ্টির সূচনা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "52",
      "chSerial": "49",
      "bookId": "1",
      "hadith_number": "127",
      "range_start": "2964",
      "range_end": "3090",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Prophets",
      "nameBengali": "৫০/ আম্বিয়া কিরাম (আঃ)",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "53",
      "chSerial": "50",
      "bookId": "1",
      "hadith_number": "573",
      "range_start": "3091",
      "range_end": "3663",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish":
          "Military Expeditions led by the Prophet (pbuh) (Al-Maghaazi)",
      "nameBengali": "৫১/ মাগাযী (যুদ্ধাভিযান)",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "54",
      "chSerial": "51",
      "bookId": "1",
      "hadith_number": "458",
      "range_start": "3664",
      "range_end": "4121",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish":
          "Prophetic Commentary on the Qur'an (Tafseer of the Prophet  [pbuh] )",
      "nameBengali": "৫২/ তাফসীর",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "56",
      "chSerial": "52",
      "bookId": "1",
      "hadith_number": "496",
      "range_start": "4122",
      "range_end": "4613",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "53/ Virtues Of The Qur'An ",
      "nameBengali": "৫৩/ ফাজায়ীলুল কুরআন",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "57",
      "chSerial": "53",
      "bookId": "1",
      "hadith_number": "79",
      "range_start": "4614",
      "range_end": "4692",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Wedlock, Marriage (Nikaah)",
      "nameBengali": "৫৪/ বিয়ে-শাদী",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "58",
      "chSerial": "54",
      "bookId": "1",
      "hadith_number": "178",
      "range_start": "4693",
      "range_end": "4870",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Divorce",
      "nameBengali": "৫৫/ তালাক",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "59",
      "chSerial": "55",
      "bookId": "1",
      "hadith_number": "85",
      "range_start": "4875",
      "range_end": "4959",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Supporting The Family ",
      "nameBengali": "৫৬/ ভরণ পোষণ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "60",
      "chSerial": "56",
      "bookId": "1",
      "hadith_number": "22",
      "range_start": "4960",
      "range_end": "4981",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Food, Meals",
      "nameBengali": "৫৭/ আহার সংক্রান্ত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "62",
      "chSerial": "57",
      "bookId": "1",
      "hadith_number": "89",
      "range_start": "4982",
      "range_end": "5070",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Sacrifice On Occasion Of Birth (Aquqa)",
      "nameBengali": "৫৮/ আকীকা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "63",
      "chSerial": "58",
      "bookId": "1",
      "hadith_number": "9",
      "range_start": "5071",
      "range_end": "5079",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Hunting, Slaughtering",
      "nameBengali": "৫৯/ যবাহ করা, শিকার করা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "64",
      "chSerial": "59",
      "bookId": "1",
      "hadith_number": "67",
      "range_start": "5080",
      "range_end": "5146",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Al-Adha Festival Sacrifice (Adaahi)",
      "nameBengali": "৬০/ কুরবানী",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "65",
      "chSerial": "60",
      "bookId": "1",
      "hadith_number": "28",
      "range_start": "5147",
      "range_end": "5174",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Drinks",
      "nameBengali": "৬১/ পানীয় দ্রব্যসমূহ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "66",
      "chSerial": "61",
      "bookId": "1",
      "hadith_number": "63",
      "range_start": "5175",
      "range_end": "5237",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Patients",
      "nameBengali": "৬২/ রোগীদের বর্ণনা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "67",
      "chSerial": "62",
      "bookId": "1",
      "hadith_number": "38",
      "range_start": "5238",
      "range_end": "5275",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Medicine",
      "nameBengali": "৬৩/ চিকিৎসা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "68",
      "chSerial": "63",
      "bookId": "1",
      "hadith_number": "91",
      "range_start": "5276",
      "range_end": "5366",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Dress",
      "nameBengali": "৬৪/ পোষাক-পরিচ্ছদ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "69",
      "chSerial": "64",
      "bookId": "1",
      "hadith_number": "178",
      "range_start": "5367",
      "range_end": "5544",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Good Manner And From (Al- Adab)",
      "nameBengali": "৬৫/ আচার ব্যবহার",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "70",
      "chSerial": "65",
      "bookId": "1",
      "hadith_number": "249",
      "range_start": "5545",
      "range_end": "5793",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Asking Permission",
      "nameBengali": "৬৬/ অনুমতি চাওয়া",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "71",
      "chSerial": "66",
      "bookId": "1",
      "hadith_number": "72",
      "range_start": "5794",
      "range_end": "5865",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Invocations",
      "nameBengali": "৬৭/ দু’আ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "72",
      "chSerial": "67",
      "bookId": "1",
      "hadith_number": "104",
      "range_start": "5866",
      "range_end": "5969",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "To Make The Heart Tender (Ar-Riqaq)",
      "nameBengali": "৬৮/ কোমল হওয়া",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "73",
      "chSerial": "68",
      "bookId": "1",
      "hadith_number": "157",
      "range_start": "5970",
      "range_end": "6126",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Haudge",
      "nameBengali": "৬৯/ হাউয",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "74",
      "chSerial": "69",
      "bookId": "1",
      "hadith_number": "15",
      "range_start": "6127",
      "range_end": "6141",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Divine Will (Al-Qadar)",
      "nameBengali": "৭০/ তাকদির",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "75",
      "chSerial": "70",
      "bookId": "1",
      "hadith_number": "26",
      "range_start": "6142",
      "range_end": "6167",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Oaths and Vows",
      "nameBengali": "৭১/ শপথ ও মানত",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "76",
      "chSerial": "71",
      "bookId": "1",
      "hadith_number": "83",
      "range_start": "6168",
      "range_end": "6250",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Expiation For Unfulfilled Oaths",
      "nameBengali": "৭২/ শপথের কাফফারা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "77",
      "chSerial": "72",
      "bookId": "1",
      "hadith_number": "17",
      "range_start": "6251",
      "range_end": "6267",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Laws of Inheritance (Al-Faraa'id)",
      "nameBengali": "৭৩/ উত্তরাধিকার",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "78",
      "chSerial": "73",
      "bookId": "1",
      "hadith_number": "47",
      "range_start": "6268",
      "range_end": "6314",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Limits and Punishments set by Allah (Hudood)",
      "nameBengali": "৭৪/ শরীয়তের শাস্তি",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "79",
      "chSerial": "74",
      "bookId": "1",
      "hadith_number": "31",
      "range_start": "6315",
      "range_end": "6345",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish":
          "Punishment of Disbelievers at War with Allah and His Apostle ",
      "nameBengali": "৭৫/ কাফের ও ধর্মত্যাগী",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "80",
      "chSerial": "75",
      "bookId": "1",
      "hadith_number": "50",
      "range_start": "6346",
      "range_end": "6395",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Blood Money (Ad-Diyat)",
      "nameBengali": "৭৬/ রক্তপন",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "81",
      "chSerial": "76",
      "bookId": "1",
      "hadith_number": "54",
      "range_start": "6396",
      "range_end": "6449",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Apostates",
      "nameBengali":
          "৭৭/ আল্লাহদ্রোহী ও ধর্মত্যাগীদেরকে তওবার প্রতি আহবান ও তাদের সাথে যুদ্ধ",
      "lastUpdate": "2016-07-31",
      "isActive": "1",
      "id": "82",
      "chSerial": "77",
      "bookId": "1",
      "hadith_number": "21",
      "range_start": "6450",
      "range_end": "6470",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Saying Something Under Compulsion (Ikraah)",
      "nameBengali": "৭৮/ বল-প্রয়োগে বাধ্য করা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "83",
      "chSerial": "78",
      "bookId": "1",
      "hadith_number": "12",
      "range_start": "6471",
      "range_end": "6482",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Tricks",
      "nameBengali": "৭৯/ কূটকৌশল",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "84",
      "chSerial": "79",
      "bookId": "1",
      "hadith_number": "28",
      "range_start": "6483",
      "range_end": "6510",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Interpretation of Dreams",
      "nameBengali": "৮০/ স্বপ্নের ব্যাখ্যা প্রদান",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "85",
      "chSerial": "80",
      "bookId": "1",
      "hadith_number": "61",
      "range_start": "6511",
      "range_end": "6571",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Afflictions And The End Of The Warld",
      "nameBengali": "৮১/ ফিতনা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "86",
      "chSerial": "81",
      "bookId": "1",
      "hadith_number": "80",
      "range_start": "6572",
      "range_end": "6651",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Judgements (Ahkaam)",
      "nameBengali": "৮২/ আহকাম",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "87",
      "chSerial": "82",
      "bookId": "1",
      "hadith_number": "80",
      "range_start": "6652",
      "range_end": "6731",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Wishes",
      "nameBengali": "৮৩/ আকাঙ্ক্ষা",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "88",
      "chSerial": "83",
      "bookId": "1",
      "hadith_number": "20",
      "range_start": "6732",
      "range_end": "6751",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Accepting Information Given By A Truthful Person",
      "nameBengali": "৮৪/ খবরে ওয়াহিদ",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "89",
      "chSerial": "84",
      "bookId": "1",
      "hadith_number": "20",
      "range_start": "6752",
      "range_end": "6771",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Holding Fast To The Qur'An And Sunnah",
      "nameBengali": "৮৫/ কুরআন ও সুন্নাহকে দৃঢ়ভাবে ধারন",
      "lastUpdate": "2015-05-13",
      "isActive": "1",
      "id": "90",
      "chSerial": "85",
      "bookId": "1",
      "hadith_number": "96",
      "range_start": "6772",
      "range_end": "6867",
      "bookInitial": "bukhari"
    },
    {
      "nameEnglish": "Oneness, Uniqueness Of Allah (Tawheed)",
      "nameBengali": "৮৬/ জাহ্‌মিয়াদের মতের খণ্ডন ও তাওহীদ প্রসঙ্গ",
      "lastUpdate": "2016-08-01",
      "isActive": "1",
      "id": "91",
      "chSerial": "86",
      "bookId": "1",
      "hadith_number": "186",
      "range_start": "6868",
      "range_end": "7053",
      "bookInitial": "bukhari"
    }
  ];
}
